name: build_alpine
on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu-utils
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils wget -y; cd ~/ ;wget https://raw.githubusercontent.com/alpinelinux/alpine-make-vm-image/v0.9.0/alpine-make-vm-image

      - uses: actions/checkout@v2
      - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.ACC_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./my-artifact.zip
        asset_name: my-artifact.zip
        asset_content_type: application/zip

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACC_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}

      - name: Build image
        run: |
         sudo bash ~/alpine-make-vm-image \
              --image-format qcow2 \
              --image-size 1024G \
              --packages "$(cat example/packages)" \
              --kernel-flavor lts \
              --branch 3.16 \
              alpine-$(date +%Y-%m-%d).qcow2
