name: ubunturdptest
on:
  workflow_dispatch:
    inputs:
      msg:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
        - name: Checkout

      uses: actions/checkout@v3

      - name: SSH Keepalive Hack

      run: |

        mkdir -p ~/.ssh

        cat << EOF > ~/.ssh/config

        Host *

            ServerAliveInterval 60

            StrictHostKeyChecking no

        Host github.com

            User git

            Port 22

            Hostname github.com

            TCPKeepAlive yes

            IdentitiesOnly yes

        EOF

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - uses: actions/checkout@v3

      - name: Add user

      run: |

        apt install sudo -y ;sudo useradd -m ash && sudo adduser ash sudo && echo 'ash:ash' | sudo chpasswd

      # Runs a single command using the runners shell

      - name: Update System

        run: apt update; apt full-upgrade -y

      # Runs a set of commands using the runners shell

      - name: Installing Desktop 

        run: | 

          apt install sudo -y; sudo apt install ubuntu-gnome-desktop gnome -y;

          wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb -P /tmp

          sudo apt install /tmp/chrome-remote-desktop_current_amd64.deb -y; mkdir ~/.config/chrome-remote-desktop

          sudo apt install expect -y

       - name: generate script

      run: |

           touch setup.sh

           echo "${{ github.event.inputs.auth }}" >> "setup.sh"

           chmod 777 setup.sh

    - name: initialize GRDP

      run: |   

           expect -c '

           spawn ./setup.sh

           expect "Enter a PIN of at least six digits: "

           send "123456\r"

           expect "Enter the same PIN again: "

           send "123456\r"

           expect eof

           '

     - name: Start SSH via ngrok

      continue-on-error: true

      timeout-minutes: 99999999999999999999999999999999999999999999999999

      uses: P3TERX/ssh2actions@main

      with:

        mode: ngrok

      env:

        # You can find this token here: https://dashboard.ngrok.com/auth/your-authtoken

        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}

        # ngrok server region [us, eu, au, ap, sa, jp, in] (optional, default: us)

        NGROK_REGION: in

        # This password you will use when authorizing via SSH

        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

        # Send connection info to Telegram (optional)

        #TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

        #TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      
